resolver: lts-10.0

packages:
  - '.'
  - location:
      git: https://github.com/airalab/hs-web3
      commit: 45343b2bb7821f2643be0d78a8a4f544603c9139
    extra-dep: true

extra-deps:
  - selda-0.1.11.2
  - sized-0.2.1.1
  - equational-reasoning-0.5.0.0
  - monomorphic-0.0.3.3
  - type-natural-0.7.1.4
  - presburger-1.3.1
  - ghc-typelits-presburger-0.1.1.1
